### ISSUE TITLE
Version Numbering

### ISSUE THREAD

**Issue by yahyaerturan** [duncanmcdougall/Responsive-Lightbox#21]
Dear McDougall,

Great work, I liked it the moment I saw the blurring effect which I used in the app that I am developing nowadays.

We, you actually, should versionise it. Let me know If I can assits.

On the other hand, is it working with BS3 and jQuery 2?

**Comment by duncanmcdougall** [comment]
Having tested it out briefly with the latest bootstrap and jQuery 2 tonight it works fine for me. 

The current version is 1.1. I'm planning on cleaning up the CSS  bit this week then I'll make it v1.2
