### ISSUE TITLE
swipe option?

### ISSUE THREAD

**Issue by es88** [duncanmcdougall/Responsive-Lightbox#22]
Hi Duncan,

First of all - thanks for sharing. Really like the lightweight approach.
However it is not really an issue, I would like to know if there is a simple way to include a swipe option to make it more accessible on mobile?

Thanks,
Eva

**Comment by duncanmcdougall** [comment]
There is no swipe support built in but the lightbox code should be simple enough to add in your own events to trigger next and previous when swiping on the plugin. If you do add any support yourself I'd love to have a look at your code and see if I can build it in.

**Comment by es88** [comment]
Hi Duncan. Thanks you getting back. Appreciated. Have opted for a neater version for mobile.
Thank you.
