### ISSUE TITLE
Attribution requires leaving author name, author homepage link, and the license info intact

### ISSUE THREAD

**Issue by jslegers** [duncanmcdougall/Responsive-Lightbox#8]
So what exactly does this mean? Is it OK to have author name, author homepage link, and license info in just the JS file? Or do I need to add it elsewhere?

I'm considering integrating your responsive lightbox into an MIT licensed project ( http://www.cascade-framework.com/ ), but I'm not entirely comfortable with your CC Attribution license as this license is notoriously ambiguous and could conflict with my own license of that of people who want to use my framework.

Would you consider replacing your CC Attribution license with an MIT, BSD, Apache, LGPL or similar license? IMO such licenses are far more suitable for code libraries as they're less likely to conflict with other licenses.

**Comment by hadiS** [comment]
Hi, sorry to reopen, but is this great plugin now under MIT or under CC Attribution licence? On the github readme it says MIT, in your JS files it says CC. 

Anyway can I use this plugin in all kind of projects? Even in commercially used projects?

Thanks.

**Comment by duncanmcdougall** [comment]
Yes. Feel free to use it in commercial project. 
Thanks for making me aware of this. I'll fix into the licensing inconsistency.
